{% set name = "pyobsplot" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobsplot-{{ version }}.tar.gz
  sha256: 6a63c076569e7a8446b8497ee558fb667b5e51feba2e77830c19dcc0123ea5a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - anywidget >=0.6.5,<0.7.0
    - pandas >=1.2.0
    - polars >=0.16.0
    - pyarrow >=11.0.0,<12.0.0
    - ipywidgets >=8.1.0
    - jupyterlab_widgets >=3.0.0
    - jupyterlab >=3.6.0
    - requests >=2.28.2,<3.0.0

test:
  imports:
    - pyobsplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juba/pyobsplot
  summary: Observable Plot in Jupyter notebooks and Quarto documents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
