{% set name = "pyobsplot" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyobsplot-{{ version }}.tar.gz
  sha256: 7e35e7ea0511bdaa232d367e4da35c8eaaba02722b3769191a1f3d44c17fd971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9.0
    - anywidget ==0.9.0
    - pandas >=1.2.0
    - polars >=0.20.0
    - pyarrow ==15.0.0
    - requests >=2.28.2,<3.0.0

    # From anywidget[dev]
    - comm >=0.1.0
    - watchfiles >=0.18.0

test:
  imports:
    - pyobsplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juba/pyobsplot
  summary: Observable Plot in Jupyter notebooks and Quarto documents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
