{% set python_min = "3.10" %}
{% set name = "pyobsplot" %}
{% set version = "0.5.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyobsplot-{{ version }}.tar.gz
  sha256: 0527a3f658d397f83f5117fe2bb39d75e15d90d357acaaff66341d777ced99e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.18
    - pandas >=2.0.0
    - polars >=1.4.1
    - requests
    # Use typst-py instead of typst, the latter is the native package and the former is python bindings
    - typst-py >=0.11.1
    - pyarrow ==18.1.0

    # From anywidget[dev]
    - comm >=0.1.0
    - watchfiles >=0.18.0

test:
  imports:
    - pyobsplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/juba/pyobsplot
  doc_url: https://juba.github.io/pyobsplot
  summary: Observable Plot in Jupyter notebooks and Quarto documents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
